
export default [
  {
    img: 'img/theme/bootstrap.jpg',
    title: '1',
    budget: 'PROC_202102031230',
    status: '待確認',
    statusType: 'warning',
    completion: 60,
    apprvName: '王O慶',
    apprvResult: '',
  },
  {
    img: 'img/theme/angular.jpg',
    title: '2',
    budget: 'PROC_202102031333',
    status: '已完成',
    statusType: 'success',
    completion: 100,
    apprvName: '王O慶',
    apprvResult: '同意',
  },
  {
    img: 'img/theme/sketch.jpg',
    title: '3',
    budget: 'PROC_202102031832',
    status: '退件待確認',
    statusType: 'danger',
    completion: 72,
    apprvName: '李O輝',
    apprvResult: '駁回',
  },
  {
    img: 'img/theme/react.jpg',
    title: '4',
    budget: 'PROC_202102031431',
    status: '已更新',
    statusType: 'info',
    completion: 90,
    apprvName: '陳O毅',
    apprvResult: '',
  },
  {
    img: 'img/theme/vue.jpg',
    title: '5',
    budget: 'PROC_202102041634',
    status: '已完成',
    statusType: 'success',
    completion: 100,
    apprvName: '李O輝',
    apprvResult: '同意',
  },
  {
    img: 'img/theme/bootstrap.jpg',
    title: '6',
    budget: 'PROC_202102041764',
    status: '待確認',
    statusType: 'warning',
    completion: 60,
    apprvName: '李O輝',
    apprvResult: '',
  },
  {
    img: 'img/theme/angular.jpg',
    title: '7',
    budget: 'PROC_202102063264',
    status: '已完成',
    statusType: 'success',
    completion: 100,
    apprvName: '陳O毅',
    apprvResult: '同意',
  },
  {
    img: 'img/theme/sketch.jpg',
    title: '8',
    budget: 'PROC_202102063482',
    status: '退件待確認',
    statusType: 'danger',
    completion: 72,
    apprvName: '王O慶',
    apprvResult: '駁回',
  },
  {
    img: 'img/theme/vue.jpg',
    title: '9',
    budget: 'PROC_202102086612',
    status: '已完成',
    statusType: 'success',
    completion: 100,
    apprvName: '王O慶',
    apprvResult: '同意',
  }
]
